### Registro de usuario
@BASE_URL = http://localhost:3000/api/v1
@CONTENT_TYPE = application/json

POST {{BASE_URL}}/auth/register
Content-Type: {{CONTENT_TYPE}}

{
  "email": "test@example.com",
  "password": "password123",
  "nombreCompleto": "Test Usuario"
}

### Login
POST {{BASE_URL}}/auth/login
Content-Type: {{CONTENT_TYPE}}

{
  "email": "test@example.com",
  "password": "password123"
}

### Get Me
GET {{BASE_URL}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEsImlhdCI6MTc3NzA2NzczMywiZXhwIjoxNzc3MDcxMzMzfQ.r0fFDqbfK4cRm1pMSz1xA3Y-sRh179zPii6Enc7SLUA